version: 2.1
jobs:
  build_dev:
    machine: true
    working_directory: ~/iqueensu-dev-build
    steps:
      - checkout
      - run:
          name: Django Migrate
          command: docker-compose run web python manage.py migrate
      - run:
          name: Create Super User
          command: |
            csu_prefix="from django.contrib.auth.models import User; User.objects.create_superuser("
            csu_vars="'${DEFAULT_DJANGO_SUPERUSER_NAME}', '${DEFAULT_DJANGO_SUPERUSER_EMAIL}', '${DEFAULT_DJANGO_SUPERUSER_PASSWD}')"
            echo "${csu_prefix}${csu_vars}"

workflows:
# workflows version Should currently(2020-1-25) be 2
# https://circleci.com/docs/2.0/configuration-reference/#workflows:
  version: 2
  deploy_dev:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - circle-test
                - dev-deploy
      #- release_deploy:
          # leaved blank for further configuration
