version: 2.1
jobs:
  build:
    docker:
      - inmage: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
    branches:
      only:
      - circle-test
      - test-deploy
