# Generated by Django 2.1.2 on 2018-10-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_author', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
