# Generated by Django 2.2 on 2019-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_author', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
