# Generated by Django 2.1.2 on 2018-11-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpost',
            name='id',
        ),
        migrations.AddField(
            model_name='qpost',
            name='post_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
