# Generated by Django 3.0.3 on 2020-02-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QCumber', '0005_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QCumber.CourseDetail'),
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_review', models.TextField(null=True)),
                ('star_ratings', models.SmallIntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QCumber.Course')),
            ],
        ),
    ]
