# Generated by Django 3.0.3 on 2020-02-21 02:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("QCumber", "0005_remove_uuid_null")]

    operations = [
        migrations.CreateModel(
            name="CourseRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2020,
                        validators=[
                            django.core.validators.MinValueValidator(2014),
                            django.core.validators.MaxValueValidator(2021),
                        ],
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FALL", "Fall"),
                            ("WINTER", "Winter"),
                            ("SUMMER", "Summer"),
                        ],
                        default="FALL",
                        max_length=50,
                    ),
                ),
                ("prof", models.CharField(blank=True, max_length=128)),
                ("course_review", models.TextField(null=True)),
                ("star_ratings", models.SmallIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="QCumber.Course",
                    ),
                ),
            ],
        )
    ]
