"""
add uuid_text in gradeDistribution table
"""
# Generated by Django 3.0.3 on 2020-04-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    """migration"""
    dependencies = [
        ('QCumber', '0006_auto_20200301_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedistribution',
            name='uuid_text',
            field=models.TextField(null=True),
        ),
    ]
