# Generated by Django 3.0.3 on 2020-02-18 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCumber', '0006_auto_20200218_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='term',
            field=models.CharField(choices=[(1, 'Fall'), (2, 'Winter'), (3, 'Summer')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='courserating',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
