# Generated by Django 3.0.3 on 2020-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCumber', '0008_courserating_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='prof',
            field=models.CharField(blank=True, choices=[('SELECT', 'Please select'), ('YUANTIAN', 'Yuan Tian'), ('TINGHU', 'Ting Hu')], default='SELECT', max_length=50),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='term',
            field=models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('SUMMER', 'Summer')], default='FALL', max_length=50),
        ),
    ]
